### PR TITLE
Feed pagination implementation

### PR DESCRIPTION
**Pull request by igeligel**
Notable changes:

- added `yarn.lock` file for yarn users
- added new component `Pagination` which will handle the pagination, not bound to vuex or similar to keep it seperated
- Pagination is working for global feed and popular tags also

### CODE REVIEW

**Comment by vilsbole** [comment]
@igeligel that's great! I just pushed the implementation of the styleguide which might cause some conflicts. Could you resolve them first so I can accept the PR?

**Comment by igeligel** [comment]
Fixed by merging remote master

**Comment by vilsbole** [comment]
[**Bug Report**] When I go to page 2, then view a tag feed, the page index is not reset

**Comment by igeligel** [comment]
Good catch 👍 Fixed it

**Pull request merged**
